<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PackageId>QuickLinker.$(AssemblyName)</PackageId>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Authors>QuickLinker.$(AssemblyName)</Authors>
    <Product>QuickLinker.$(AssemblyName)</Product>
  </PropertyGroup>

</Project>
