//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickLinker.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickLinker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 确定要清除此按钮的配置吗? 的本地化字符串。
        /// </summary>
        internal static string BtnPropertiesFrom_Clear {
            get {
                return ResourceManager.GetString("BtnPropertiesFrom_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组 {0} 的本地化字符串。
        /// </summary>
        internal static string BtnPropertiesFrom_GroupDefName {
            get {
                return ResourceManager.GetString("BtnPropertiesFrom_GroupDefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序文件(*.exe)|*.exe|所有文件(*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string BtnPropertiesFrom_OpenFile {
            get {
                return ResourceManager.GetString("BtnPropertiesFrom_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组 {0}，按钮 {1} 的属性 的本地化字符串。
        /// </summary>
        internal static string BtnPropertiesFrom_Title {
            get {
                return ResourceManager.GetString("BtnPropertiesFrom_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] CUR_COPY {
            get {
                object obj = ResourceManager.GetObject("CUR_COPY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 存在TurboLaunch配置,是否使用该配置进行初始化? 的本地化字符串。
        /// </summary>
        internal static string FromTurboLaunch_Switch {
            get {
                return ResourceManager.GetString("FromTurboLaunch_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标文件|*.exe*.icon*.dll|所有文件(*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string IconFrom_OpenFile {
            get {
                return ResourceManager.GetString("IconFrom_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在排列：请点击目标按钮 的本地化字符串。
        /// </summary>
        internal static string MainForm_AlignStats {
            get {
                return ResourceManager.GetString("MainForm_AlignStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已选择复制：
        ///
        ///{0}
        ///
        ///到按钮上，此按钮已分配给：
        ///
        ///{1}
        ///
        ///确认要替换配置信息吗？ 的本地化字符串。
        /// </summary>
        internal static string MainForm_Copy {
            get {
                return ResourceManager.GetString("MainForm_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在复制：请点击目标按钮 的本地化字符串。
        /// </summary>
        internal static string MainForm_CopyStats {
            get {
                return ResourceManager.GetString("MainForm_CopyStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要清除以下按钮吗？
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string MainForm_Remove {
            get {
                return ResourceManager.GetString("MainForm_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在交换：请点击目标按钮 的本地化字符串。
        /// </summary>
        internal static string MainForm_SwitchStats {
            get {
                return ResourceManager.GetString("MainForm_SwitchStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于(&amp;A)... 的本地化字符串。
        /// </summary>
        internal static string MainForm_SysMenu_About {
            get {
                return ResourceManager.GetString("MainForm_SysMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除标题栏(&amp;B) 的本地化字符串。
        /// </summary>
        internal static string MainForm_SysMenu_RemoveSysMenu {
            get {
                return ResourceManager.GetString("MainForm_SysMenu_RemoveSysMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首选项(&amp;P)... 的本地化字符串。
        /// </summary>
        internal static string MainForm_SysMenu_Setting {
            get {
                return ResourceManager.GetString("MainForm_SysMenu_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总在最前面(&amp;T) 的本地化字符串。
        /// </summary>
        internal static string MainForm_SysMenu_TopMost {
            get {
                return ResourceManager.GetString("MainForm_SysMenu_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string MSGBox_Tip {
            get {
                return ResourceManager.GetString("MSGBox_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;未配置&gt; 的本地化字符串。
        /// </summary>
        internal static string TPanel_None {
            get {
                return ResourceManager.GetString("TPanel_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream WAVE_BUTTON {
            get {
                return ResourceManager.GetStream("WAVE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream WAVE_CLICK {
            get {
                return ResourceManager.GetStream("WAVE_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream WAVE_CONNECT {
            get {
                return ResourceManager.GetStream("WAVE_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream WAVE_DISCONNECT {
            get {
                return ResourceManager.GetStream("WAVE_DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream WAVE_DROP {
            get {
                return ResourceManager.GetStream("WAVE_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream WAVE_GROUP {
            get {
                return ResourceManager.GetStream("WAVE_GROUP", resourceCulture);
            }
        }
    }
}
